blank_issues_enabled: false # Impede que os usu치rios criem issues sem usar um template
contact_links:
  - name: 游 Adicionar Novo Site
    url: https://github.com/deividgabrielpeira/fontes-de-anime-e-mangas/issues/new?assignees=&labels=Novo+Site&template=adicionar-novo-site.yml&title=%F0%9F%86%95+Sugerir+Novo+Site
    about: Sugerir a adi칞칚o de um novo site de anime/mang치/manhua ao cat치logo.
  - name: 游냍 Reportar Bug
    url: https://github.com/deividgabrielpeira/fontes-de-anime-e-mangas/issues/new?assignees=&labels=Bug&template=reportar-bug.yml&title=%F0%9F%90%9B+[Bug]+Descri칞칚o+curta+do+problema
    about: Reportar um problema ou bug no reposit칩rio.